[[constraint]]
  name = "github.com/hashicorp/vault"
  revision = "e21712a687889de1125e0a12a980420b1a4f72d3"

[[constraint]]
  name = "github.com/hashicorp/go-hclog"
  revision = "ff2cf002a8dd750586d91dddd4470c341f981fe1"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  revision = "19abc56a8cd8d3630ab9735173cb92c0bf635f33"

[[constraint]]
  name = "github.com/gophercloud/utils"
  revision = "18450e98e12dae90303d0483730333797d04be9b"
