version: '2'

tasks:
  build:
    cmds:
      - go build .
  test:
    cmds:
      - go vet ./plugin
      - go test -coverprofile=cover.out ./plugin
  cover:
    deps: [test]
    cmds:
      - go tool cover -html=cover.out
  package:
    cmds:
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build .
      - shasum -a 256 vault-plugin-auth-openstack > sha256sum.txt
      - tar -czf dist/vault-plugin-auth-openstack_{{.OS}}_{{.ARCH}}.tar.gz vault-plugin-auth-openstack sha256sum.txt
      - echo `cat sha256sum.txt` "({{.OS}}_{{.ARCH}})"
      - rm -rf vault-plugin-auth-openstack sha256sum.txt
  dist:
    deps: [test]
    cmds:
      - mkdir -p dist
      - task: package
        vars: {OS: "linux", ARCH: "amd64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm"}
      - task: package
        vars: {OS: "darwin", ARCH: "amd64"}
  vendor:
    cmds:
      - dep ensure -v
  clean:
    cmds:
      - rm -rf vault-plugin-auth-openstack dist cover.out
