version: '2'

vars:
  NAME: vault-plugin-auth-openstack

tasks:
  build:
    cmds:
      - go build .
  test:
    cmds:
      - go vet ./...
      - go test -v -coverprofile=cover.out ./...
  cover:
    deps: [test]
    cmds:
      - go tool cover -html=cover.out
  package:
    cmds:
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build .
      - shasum -a 256 {{.NAME}} > sha256sum.txt
      - tar -czf dist/{{.NAME}}_{{.OS}}_{{.ARCH}}.tar.gz {{.NAME}} sha256sum.txt
      - echo `cat sha256sum.txt` "({{.OS}}_{{.ARCH}})"
      - rm -rf {{.NAME}} sha256sum.txt
  dist:
    deps: [test]
    cmds:
      - mkdir -p dist
      - task: package
        vars: {OS: "linux", ARCH: "amd64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm"}
      - task: package
        vars: {OS: "darwin", ARCH: "amd64"}
  vendor:
    cmds:
      - dep ensure -v
  clean:
    cmds:
      - rm -rf {{.NAME}} dist cover.out
